[package]
name = "gmres"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.0"
ndarray-linalg = { version = "0.14", features = ["openblas-static"] }
num-traits = "0.2"

[dev-dependencies]
ndarray-rand = "0.14.0"